apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    chart: opencost
    targetRevision: "1.43.0"
    helm:
      values: |
        prometheus:
          server:
            enabled: false
        opencost:
          externalPrometheus:
            enabled: true
            address: http://monitoring-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
          metrics:
            emitPodAnnotations: false
            emitNamespaceAnnotations: false
        kubecostModel:
          warmCache: true
          warmSavingsCache: true
        extraEnv:
          - name: PROMETHEUS_SERVER_ENDPOINT
            value: http://monitoring-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
          - name: QUERY_WINDOW_DAYS
            value: "7"
          - name: DATA_RETENTION_DAILY_RESOLUTION_DAYS
            value: "7"
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
