apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shelfware-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/PXL-Systems-Expert/2526-ex-DemirEvren.git
    targetRevision: main
    path: INFRA/argocd/applications/appcluster
    directory:
      recurse: false
      include: '*.yaml'
      exclude: 'root-app.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true