apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shelfware-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/PXL-Systems-Expert/2526-ex-DemirEvren.git
    targetRevision: main
    path: INFRA/kustomize/shelfware/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test-shelfware
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true