apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:16-alpine
        command:
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgres -U postgres -p 5432; do
            echo "  PostgreSQL is unavailable - sleeping..."
            sleep 2
          done
          echo "✓ PostgreSQL is ready!"
      - name: db-migration
        image: ghcr.io/demirevren/shelfware-backend:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          echo "Running database migrations..."
          npx prisma migrate deploy
          
          echo "Seeding database..."
          npx prisma db seed || echo "Seed failed or already seeded"
          
          echo "✓ Database initialization complete!"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database-url
      containers:
      - name: backend
        image: ghcr.io/demirevren/shelfware-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: jwt-secret
        - name: BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: BACKEND_PORT
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: CORS_ORIGIN
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
      - name: prometheus-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          name: metrics
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi