apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust
      role: worker
  template:
    metadata:
      labels:
        app: locust
        role: worker
    spec:
      containers:
        - name: locust
          image: locustio/locust:2.24.1
          args:
            - "-f"
            - "/mnt/locust/locustfile.py"
            - "--worker"
            - "--master-host=locust-master"
          env:
            - name: TARGET_ENV
              value: "prod"
            - name: HOST_HEADER
              value: "shelfware.local"
            - name: BASE_URL
              value: "http://istio-ingressgateway.istio-system.svc.cluster.local"
          volumeMounts:
            - name: locust-script
              mountPath: /mnt/locust
      volumes:
        - name: locust-script
          configMap:
            name: locust-config
