apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: master
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      containers:
      - name: locust
        image: locustio/locust:2.24.1
        args:
          - "-f"
          - "/mnt/locust/locustfile.py"
          - "--master"
        ports:
          - containerPort: 8089
          - containerPort: 5557
        volumeMounts:
          - name: locust-script
            mountPath: /mnt/locust
      volumes:
        - name: locust-script
          configMap:
            name: locust-config
