apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loadtest-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/DemirEvren/sqli-analyse.git
    targetRevision: main
    path: INFRA/kustomize/locust/overlays/loadtest

  destination:
    server: https://kubernetes.default.svc
    namespace: locust

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
